# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bace73c1c8db7c2451bf22fa1156d1a4843061c1ef2d77d9bb1faf0e16c995ce0a82cc653c31f4d66b4976a85d59854c7ced8cdc4db606c6326d9c0ba618d0d2

test:
  secret_key_base: 8553993594074f0b3deca157bf808b00447546fc6dbdee9873cf04432c9ca37ed2e6a28545d73da90d2417aec149c99f3d61684615bb09ebcaee8d7bac3a7e7d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
